name: SILT CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  ANACONDA_INSTALLER: Anaconda3-2023.03-1-Linux-x86_64.sh
  ANACONDA_URL: https://repo.anaconda.com/archive/${ANACONDA_INSTALLER}
  SILT_ENV: silt

jobs:
  install_silt:
    name: Install Silt
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Check env
      run: |
        pwd
        ls -la
    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('etc/example-environment.yml') }}
    - name: Setup Miniconda environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        environment-file: ./environment.yml
        # Environment name (or path) to activate on all shells. Default is `test` which will be created in `$CONDA/envs/test`. If an empty string is used, no environment is activated by default (For `base` activation see the `auto-activate-base` option). If the environment does not exist, it will be created and activated. If `environment-file` is used and you want that to be the environment used, you need to explicitely provide the name of that environment on `activate-environment`. If using sh/bash/cmd.exe shells please read the IMPORTANT! section on the README.md! to properly activate conda environments on these shells.
        activate-environment: ${{ env.SILT_ENV }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: List conda environments
      run: |
        conda info
        conda list
    - name: Install SILT
      run: |
        pip install ./silt $PIP_FLAGS

  unit_tests:
    needs: [install_silt]
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check directory
      run: |
        ls -la
    - name: List Ananconda environments
      run: |
        conda info --envs
    - name: Setup Miniconda environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        environment-file: ./environment.yml
        # Environment name (or path) to activate on all shells. Default is `test` which will be created in `$CONDA/envs/test`. If an empty string is used, no environment is activated by default (For `base` activation see the `auto-activate-base` option). If the environment does not exist, it will be created and activated. If `environment-file` is used and you want that to be the environment used, you need to explicitely provide the name of that environment on `activate-environment`. If using sh/bash/cmd.exe shells please read the IMPORTANT! section on the README.md! to properly activate conda environments on these shells.
        activate-environment: ${{ env.SILT_ENV }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: List conda environments
      run: |
        conda info
        conda list
    - name: Install SILT
      run: |
        pip install ./silt $PIP_FLAGS
    - name: Run unit tests
      run: |
        cd silt/test
        pytest --cov=silt

  package_bundle:
    needs: [unit_tests]
    name: Package Bundle
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment
      run: |
        bash ${GITHUB_WORKSPACE}/utils/configure_conda.bash ${GITHUB_WORKSPACE}/condarc.template /home/gitlab-runner/.condarc
        ANACONDA_DIR="$(echo ${GITHUB_WORKSPACE} | sed 's|builds||g')"
        source ${ANACONDA_DIR}/anaconda3/etc/profile.d/conda.sh
        conda activate ${SILT_ENV}
    - name: Create tarball
      run: |
        make tarball_with_tests
    - uses: actions/upload-artifact@v4
      with:
        name: silt-pkg.tar.gz
        path: ./silt-pkg.tar.gz
        
  test_package_bundle:
    needs: [package_bundle]
    name: Test Package Bundle
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment
      run: |
        bash ${GITHUB_WORKSPACE}/utils/configure_conda.bash ${CI_PROJECT_DIR}/condarc.template /home/gitlab-runner/.condarc
        ANACONDA_DIR="$(echo ${GITHUB_WORKSPACE} | sed 's|builds||g')"
        source ${ANACONDA_DIR}/anaconda3/etc/profile.d/conda.sh
    - name: Test package
      run: |
        tar xf silt-pkg.tar.gz
        cd silt-pkg/
        tmpdir="$(mktemp -d)/silt"
        ./silt*.sh -b -p ${tmpdir}
        conda activate ${tmpdir}
        pytest test/
        rm -rf ${tmpdir}
