name: SILT CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  ANACONDA_INSTALLER: Anaconda3-2023.03-1-Linux-x86_64.sh
  ANACONDA_URL: https://repo.anaconda.com/archive/${ANACONDA_INSTALLER}
  SILT_ENV: silt

defaults:
      run:
        shell: bash -el {0}
        
jobs:
  install_silt:
    name: Install Silt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('etc/example-environment.yml') }}
    - name: Setup Miniconda environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        environment-file: ./environment.yml
        activate-environment: ${{ env.SILT_ENV }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: List conda environments
      run: |
        conda info
        conda list
    - name: Install SILT
      run: |
        pip install ./silt $PIP_FLAGS

  unit_tests:
    needs: [install_silt]
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Setup Miniconda environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        environment-file: ./environment.yml
        activate-environment: ${{ env.SILT_ENV }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: List conda environments
      run: |
        conda info
        conda list
    - name: Install SILT
      run: |
        pip install ./silt $PIP_FLAGS
    - name: Run unit tests
      run: |
        cd silt/test
        pytest --cov=silt

  package_bundle:
    needs: [unit_tests]
    name: Package Bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Setup Miniconda environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        environment-file: ./environment.yml
        activate-environment: ${{ env.SILT_ENV }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Install SILT
      run: |
        pip install ./silt $PIP_FLAGS
    - name: Create tarball
      run: |
        make tarball_with_tests
    - uses: actions/upload-artifact@v4
      with:
        name: silt-pkg.tar.gz
        path: ./silt-pkg.tar.gz
        
  test_package_bundle:
    needs: [package_bundle]
    name: Test Package Bundle
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment
      run: |
        bash ${GITHUB_WORKSPACE}/utils/configure_conda.bash ${CI_PROJECT_DIR}/condarc.template /home/gitlab-runner/.condarc
        ANACONDA_DIR="$(echo ${GITHUB_WORKSPACE} | sed 's|builds||g')"
        source ${ANACONDA_DIR}/anaconda3/etc/profile.d/conda.sh
    - name: Test package
      run: |
        tar xf silt-pkg.tar.gz
        cd silt-pkg/
        tmpdir="$(mktemp -d)/silt"
        ./silt*.sh -b -p ${tmpdir}
        conda activate ${tmpdir}
        pytest test/
        rm -rf ${tmpdir}
